package cn.hex.ddp.manufacture.domain.configuration.enums;

import cn.hex.ddp.manufacture.domain.common.enums.AreaEnum;
import com.baomidou.mybatisplus.annotation.EnumValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

import java.io.Serializable;

/**
 * @ClassDescription:
 * @Author: KangHong
 * @Created: 2024/6/8 1:05
 */
@AllArgsConstructor
@Getter
public enum PositionNameEnum implements Serializable {
    /**
     * 默认位置
     */
    DEFAULT(0, AreaEnum.DEFAULT),
    /**
     * 热砂合模交互点
     */
    HOT_SAND_MOLDING_POSITION(1, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂合模交互点
     */
    COLD_SAND_MOLDING_POSITION(2, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流总轨道的交互点
     */
    SAND_BOX_REFLUX_ALL_POSITION(3, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道交互点
     */
    CORE_MAKING_POSITION(4, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道放置的交互点
     */
    CORE_MAKING_LAY_POSITION(5, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道交互点
     */
    MOLD_REFLUX_POSITION(6, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂回流轨道交互点
     */
    COLD_REFLUX_POSITION(7, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂回流开箱交互点
     */
    HOT_SAND_UNBOXING_REFLUX_POSITION(8, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂冷砂混合轨道回流开箱交互点
     */
    HOT_SAND_AND_COLD_SAND_MIXED_UNBOXING_REFLUX_POSITION(9, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂垂直回流轨道交互点
     */
    HOT_SAND_VERTICAL_TRACK_REFLUX_INTERACTION_POSITION(10, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流行车放置点
     */
    SAND_BOX_ROW_CAR_POSITION(11, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流放置交互点2
     */
    SAND_MOLD_REFLUX_RAIL_INTERACTION_POSITION_2(12, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流放置交互点1
     */
    SAND_MOLD_REFLUX_RAIL_INTERACTION_POSITION_1(13, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂行车放置交互点
     */
    COLD_SAND_ROW_CAR_POSITION(14, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂射砂放置点位
     */
    HOT_SAND_SHOOTING_POSITION(15, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂射砂放置点位
     */
    COLD_SAND_SHOOTING_POSITION(16, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂模具开模模具放置点位
     */
    HOT_MOLD_OPENING_MOLD_LAY_POSITION(17, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂模具开模砂箱放置点位
     */
    HOT_MOLD_OPENING_SAND_BOX_LAY_POSITION(18, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂砂箱回流放置点位
     * 可能不存在！！！
     */
    HOT_MOLD_OPENING_SAND_BOX_REFLUX_LAY_POSITION(19, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂芯模具开模砂箱放置点位
     */
    CORE_MOLD_OPENING_MOLD_LAY_POSITION(20, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂模具开模模具放置点位
     */
    COLD_MOLD_OPENING_MOLD_LAY_POSITION(21, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂模具开模砂箱放置点位
     */
    COLD_MOLD_OPENING_SAND_BOX_LAY_POSITION(22, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂砂箱前往喷涂的下方点位
     */
    HOT_SAND_BOX_GO_SPRAY_DOWN_POSITION(23, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂砂箱前往喷涂的点位1
     */
    COLD_SAND_BOX_GO_SPRAY_POSITION_1(24, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂砂箱前往喷涂的点位2
     */
    COLD_SAND_BOX_GO_SPRAY_POSITION_2(25, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂喷涂完成前往合箱点位
     */
    HOT_SAND_BOX_SPRAY_GO_CLOSING_BOX_POSITION(26, AreaEnum.SOUTH_COMBINE_BOX),
    /**
     * 冷砂喷涂完成前往合箱点位
     */
    COLD_SAND_BOX_SPRAY_GO_CLOSING_BOX_POSITION(27, AreaEnum.SOUTH_COMBINE_BOX),
    /**
     * 热砂合箱完成前往浇筑点位
     */
    HOT_SAND_BOX_CLOSING_BOX_GO_POUR_POSITION(28, AreaEnum.SOUTH_COMBINE_BOX),
    /**
     * 冷砂合箱完成前往浇筑点位
     */
    COLD_SAND_BOX_CLOSING_BOX_GO_POUR_POSITION(29, AreaEnum.SOUTH_COMBINE_BOX),
    /**
     * 待浇筑点1-100,具体注解说明不详细展开,具体情况可查看文档
     */
    POURING_UP_FIRST_POSITION_1(30, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_2(31, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_3(32, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_4(33, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_5(34, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_6(35, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_7(36, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_8(37, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_9(38, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIRST_POSITION_10(39, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_1(40, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_2(41, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_3(42, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_4(43, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_5(44, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_6(45, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_7(46, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_8(47, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_9(48, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_SECOND_POSITION_10(49, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_1(50, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_2(51, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_3(52, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_4(53, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_5(54, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_6(55, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_7(56, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_8(57, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_9(58, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_THIRD_POSITION_10(59, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_1(60, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_2(61, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_3(62, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_4(63, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_5(64, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_6(65, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_7(66, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_8(67, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_9(68, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FOURTH_POSITION_10(69, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_1(70, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_2(71, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_3(72, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_4(73, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_5(74, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_6(75, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_7(76, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_8(77, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_9(78, AreaEnum.SOUTH_WAITING_POURING),
    POURING_UP_FIFTH_POSITION_10(79, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_1(80, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_2(81, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_3(82, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_4(83, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_5(84, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_6(85, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_7(86, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_8(87, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_9(88, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIRST_POSITION_10(89, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_1(90, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_2(91, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_3(92, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_4(93, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_5(94, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_6(95, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_7(96, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_8(97, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_9(98, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_SECOND_POSITION_10(99, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_1(100, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_2(101, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_3(102, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_4(103, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_5(104, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_6(105, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_7(106, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_8(107, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_9(108, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_THIRD_POSITION_10(109, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_1(110, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_2(111, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_3(112, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_4(113, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_5(114, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_6(115, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_7(116, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_8(117, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_9(118, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FOURTH_POSITION_10(119, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_1(120, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_2(121, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_3(122, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_4(123, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_5(124, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_6(125, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_7(126, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_8(127, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_9(128, AreaEnum.SOUTH_WAITING_POURING),
    POURING_DOWN_FIFTH_POSITION_10(129, AreaEnum.SOUTH_WAITING_POURING),
    /**
     * 冷却点1-100,具体注解说明不详细展开,具体情况可查看文档
     */
    COOLING_UP_FIRST_POSITION_1(130, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_2(131, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_3(132, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_4(133, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_5(134, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_6(135, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_7(136, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_8(137, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_9(138, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIRST_POSITION_10(139, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_1(140, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_2(141, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_3(142, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_4(143, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_5(144, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_6(145, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_7(146, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_8(147, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_9(148, AreaEnum.SOUTH_COOLING),
    COOLING_UP_SECOND_POSITION_10(149, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_1(150, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_2(151, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_3(152, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_4(153, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_5(154, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_6(155, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_7(156, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_8(157, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_9(158, AreaEnum.SOUTH_COOLING),
    COOLING_UP_THIRD_POSITION_10(159, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_1(160, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_2(161, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_3(162, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_4(163, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_5(164, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_6(165, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_7(166, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_8(167, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_9(168, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FOURTH_POSITION_10(169, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_1(170, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_2(171, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_3(172, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_4(173, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_5(174, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_6(175, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_7(176, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_8(177, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_9(178, AreaEnum.SOUTH_COOLING),
    COOLING_UP_FIFTH_POSITION_10(179, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_1(180, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_2(181, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_3(182, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_4(183, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_5(184, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_6(185, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_7(186, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_8(187, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_9(188, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIRST_POSITION_10(189, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_1(190, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_2(191, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_3(192, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_4(193, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_5(194, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_6(195, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_7(196, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_8(197, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_9(198, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_SECOND_POSITION_10(199, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_1(200, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_2(201, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_3(202, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_4(203, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_5(204, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_6(205, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_7(206, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_8(207, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_9(208, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_THIRD_POSITION_10(209, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_1(210, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_2(211, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_3(212, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_4(213, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_5(214, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_6(215, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_7(216, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_8(217, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_9(218, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FOURTH_POSITION_10(219, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_1(220, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_2(221, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_3(222, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_4(223, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_5(224, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_6(225, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_7(226, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_8(227, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_9(228, AreaEnum.SOUTH_COOLING),
    COOLING_DOWN_FIFTH_POSITION_10(229, AreaEnum.SOUTH_COOLING),
    /**
     * 热砂冷砂混合开箱点位
     */
    HOT_SAND_AND_COLD_SAND_MIXING_UNBOXING_POSITION(230, AreaEnum.SOUTH_OPEN_BOX),
    /**
     * 热砂开箱点位
     */
    HOT_SAND_UNBOXING_POSITION(231, AreaEnum.SOUTH_OPEN_BOX),
    /**
     * 热砂冷砂混合开箱回流点位
     */
    HOT_SAND_AND_COLD_SAND_MIXED_UNBOXING_REFLUX_POSITION_2(232, AreaEnum.SOUTH_OPEN_BOX),
    /**
     * 铸件回流上点位
     */
    CASTING_REFLUX_UP_POSITION(233, AreaEnum.SOUTH_OPEN_BOX),
    /**
     * 铸件回流下点位
     */
    CASTING_REFLUX_DOWN_POSITION(234, AreaEnum.SOUTH_OPEN_BOX),
    /**
     * 铸件回流垂直点位
     */
    CASTING_REFLUX_VERTICALINTERACTION_POSITION(235, AreaEnum.SOUTH_OPEN_BOX),
    /**
     * 铸件回流传输点位
     */
    CASTING_REFLUX_SHIPPING_POSITION(236, AreaEnum.SOUTH_OPEN_BOX),

    //以下是2024.12.25以后修改新增的点位枚举
    /**
     * 热砂模具开模砂箱放置点位_1
     */
    HOT_MOLD_OPENING_SAND_BOX_LAY_POSITION_1(237, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂模具开模砂箱放置点位_2
     */
    HOT_MOLD_OPENING_SAND_BOX_LAY_POSITION_2(238, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_1
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_1(239, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_2
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_2(240, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_3
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_3(241, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_4
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_4(242, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_5
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_5(243, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_6
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_6(244, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_7
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_7(245, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_8
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_8(246, AreaEnum.SOUTH_MOULDING),
    /**
     * 砂箱回流堵塞放置点位_9
     */
    SAND_BOX_REFLUX_BLOCKAGE_LAY_POSITION_9(247, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂合模工岗砂箱获取点位_1
     */
    HOT_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_1(248, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂合模工岗砂箱获取点位_2
     */
    HOT_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_2(249, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂合模工岗砂箱获取点位_3
     */
    HOT_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_3(250, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂合模工岗砂箱获取点位_4
     */
    HOT_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_4(251, AreaEnum.SOUTH_MOULDING),
    /**
     * 热砂合模工岗砂箱获取点位_5
     */
    HOT_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_5(252, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道堵塞放置点位_1
     */
    CORE_MAKING_BLOCKAGE_LAY_POSITION_1(253, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道堵塞放置点位_2
     */
    CORE_MAKING_BLOCKAGE_LAY_POSITION_2(254, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道堵塞放置点位_3
     */
    CORE_MAKING_BLOCKAGE_LAY_POSITION_3(255, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道堵塞放置点位_4
     */
    CORE_MAKING_BLOCKAGE_LAY_POSITION_4(256, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道堵塞放置点位_5
     */
    CORE_MAKING_BLOCKAGE_LAY_POSITION_5(257, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯轨道堵塞放置点位_6
     */
    CORE_MAKING_BLOCKAGE_LAY_POSITION_6(258, AreaEnum.SOUTH_MOULDING),
    /**
     * 制芯获取点位
     */
    CORE_MAKING_ACQUISITION_POSITION(259, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_1
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_1(260, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_2
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_2(261, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_3
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_3(262, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_4
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_4(263, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_5
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_5(264, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_6
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_6(265, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_7
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_7(266, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_8
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_8(267, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_9
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_9(268, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_10
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_10(269, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_11
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_11(270, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_12
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_12(271, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_13
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_13(272, AreaEnum.SOUTH_MOULDING),
    /**
     * 模具回流轨道堵塞放置点位_14
     */
    MOLD_REFLUX_BLOCKAGE_LAY_POSITION_14(273, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂合模工岗砂箱获取点位_2
     */
    COLD_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_2(274, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂合模工岗砂箱获取点位_3
     */
    COLD_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_3(275, AreaEnum.SOUTH_MOULDING),
    /**
     * 冷砂合模工岗砂箱获取点位_4
     */
    COLD_SAND_MOLD_CLOSING_WORKSTATION_ACQUISITION_POSITION_4(276, AreaEnum.SOUTH_MOULDING),

    ;

    @EnumValue
    private final Integer code;

    /**
     * 所属区域
     */
    private final AreaEnum area;
}
